# Generated by Django 3.2.9 on 2022-01-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(default='default.jpg', upload_to='profile_banners/'),
        ),
    ]
