# Generated by Django 3.2.9 on 2022-01-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220110_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(upload_to='profile_banners/'),
        ),
    ]
