# Generated by Django 3.2.9 on 2022-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(default='default_profile_banner.jpg', upload_to='profile_banners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_pics/'),
        ),
    ]
